version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: debt_management_db
    environment:
      POSTGRES_DB: debt_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
    ports:
      - "8080:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
